service: iopipe-lib-master-acceptance-test

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

functions:
  callback:
    handler: handler.callback
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextSuccess:
    handler: handler.succeed
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextFail:
    handler: handler.fail
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
  contextDone:
    handler: handler.done
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    events:
      - schedule: rate(10 minutes)
